arin2002/Hacktoberfest-2022

C++/binarySearch.cpp, JAVA/binarySearch.java
added binary search code in both java and cpp language as per  issue #2
=> added binary search

PYTHON/Selection Sort.py
=> Added Selection Sort

README.md
* Write the Instructions how to contribute in this Repo in Readme.md.
=> Update Readme.md #3

C++/Stack.cpp
=> Added the Stack Program

PYTHON/binary_search.py
=> Binary search in python

JAVA/pattern/pattern1.java, JAVA/pattern/pattern10.java, JAVA/pattern/pattern11.java, JAVA/pattern/pattern12.java, JAVA/pattern/pattern13.java, JAVA/pattern/pattern14.java, JAVA/pattern/pattern15.java, JAVA/pattern/pattern16.java, JAVA/pattern/pattern17.java, JAVA/pattern/pattern18.java, JAVA/pattern/pattern19.java, JAVA/pattern/pattern2.java, JAVA/pattern/pattern20.java, JAVA/pattern/pattern21.java, JAVA/pattern/pattern22.java, JAVA/pattern/pattern23.java, JAVA/pattern/pattern24.java, JAVA/pattern/pattern25.java, JAVA/pattern/pattern26.java, JAVA/pattern/pattern27.java, JAVA/pattern/pattern28.java, JAVA/pattern/pattern3.java, JAVA/pattern/pattern4.java, JAVA/pattern/pattern5.java, JAVA/pattern/pattern6.java, JAVA/pattern/pattern7.java, JAVA/pattern/pattern8.java, JAVA/pattern/pattern9.java
I add 28 for loop pattern programs. I hope you merge my PR.
=> add for loop pattern programs in JAVA.

JAVASCRIPT/quicksort.js
Folder for JavaScript with quicksort code.
=> Adding JavaScript folder and QuickSort Algo

PYTHON/Priority Queue.py
added python DSA code-priority queue
=> added priority queue code

JAVA/ReverseString.java
Considering various DSA Problems related to string manipulation, I have added one simple one Reverse String Code using Java.
Given a string and reverse each word at the same position without altering sequence of words.
Examples : 
Input: - Enter the String:
- This is a test string
Output: sihT si a tset gnirts
I have contributed this under hacktoberfest and also have starred your repo. Thanks for opportunity.
=> Added Reverse String Java Code

C++/AnagramCheck.cpp
C++ code to check if 2 strings are anagrams or not
=> Added AnagramCheck.cpp

C++/MatrixRotation.cpp
=> Added MatrixRotation.cpp with 2 approaches

C++/MatrixTranspose.cpp
Naive and Efficient code as per interview perspective.
=> Added MatrixTranspose.cpp with 2 approaches

C++/SpiralTraversal.cpp
one of the most famous interview question
=> Added SpiralTraversal.cpp (a must do question)

C++/selection sort.cpp
This is code for selection sort.
Please add hacktoberfest-accepted label.
=> Create selection sort.cpp

JAVASCRIPT/mergesort.js
A recursive implementation of Mergesort in JS.
=> Adding Mergesort in JS

C++/Kadane's_alg.cpp
Please check the file added of Kadane's Algorithm and update me accordingly so that I can further create files in the same manner for remaining algorithm
=> Kadane's Algorithm

JAVA/Point.java
Added the source code to find the distance between two points by inputing coordinates.
=> Created point.java

PYTHON/Stack_implementation.py
The file of STACK Implementation is added with push and pop operation.
=> Stack Implementation

DSA_USING_C/Concatenate_two_DLL.c, DSA_USING_C/Implement_Queue_using_Array .c, DSA_USING_C/Sorting/bubble_sorting.c, DSA_USING_C/Sorting/heap_sorting.c, DSA_USING_C/Sorting/insertion_sorting.c, DSA_USING_C/Sorting/merge _sorting.c, DSA_USING_C/Sorting/mergeSort using linkedlist.c, DSA_USING_C/Sorting/selection_sorting.c, DSA_USING_C/Trees/BST.c, DSA_USING_C/Trees/Balanced_Binary_Tree_using_Sorted_Array.c, DSA_USING_C/Trees/DeleteTree_postorder.c, DSA_USING_C/Trees/Implement_Binary_Tree_using_Linked_List.c, DSA_USING_C/Trees/Mirror_tree_inorder.c, DSA_USING_C/Trees/Trees, DSA_USING_C/doubly_linked_list.c, DSA_USING_C/implement_stack_using_array.c, DSA_USING_C/queue using linked list.c, DSA_USING_C/singly_linked_list.c, DSA_USING_C/stacks using linked lists.c
In this branch I have added all the C codes for the data structures and algorithm.
=> Complete DSA Using C

PYTHON/Bubble Sort
The code contains Bubble Sort in Python.
=> Bubble Sort in Python

JAVASCRIPT/linkedlist.js
Linked List basic operations in javascript
=> Basic Operations In Linked List in Java Script

JAVA/greedy/ActivitySelection.java, JAVA/greedy/DEFKIN.java, JAVA/greedy/FractionalKnapsack.java, JAVA/greedy/HuffmanEncoding.java, JAVA/greedy/JobSequencing.java, JAVA/greedy/MinPlatforms.java, JAVA/greedy/WineTrading.java, JAVA/hashing/Chaining.java, JAVA/hashing/Doraemon.java, JAVA/hashing/LinearProbing.java, JAVA/hashing/QuadraticProbing.java
This commit contains solutions and problems of greedy algorithms.
=> Greedy Solutions

C++/kthElementInTheArray.cpp
=> KthElement

JAVA/Binary search/BinarySearch.java, JAVA/Binary search/Ceiling.java, JAVA/Binary search/FirstAndLastPosition.java, JAVA/Linear search/EvenDigits.java, JAVA/Linear search/FindMin.java, JAVA/Linear search/Main.java
Task completed #20. Please review my PR.
=> Added some dsa codes

PYTHON/Insertion sort
Insertion sort algorithm in python
=> Create Insertion sort

DSA_USING_C/PostFixEval
Fixed Issue of No PostFix Evaluation code in C
=> Added PostFix Evaluation code in C

DSA_USING_C/InfixToPostfix
Easy Infix to Postfix Conversion in C
=> Added Infix to Postfix conversion code in C

DSA_USING_C/InfixToPrefix
Infix To Prefix Conversion Code in C Used By Compilers
=> Added Infix To Prefix Conversion in C

DSA_USING_C/BubbleSort
Bubble Sort Code in C with Time complexity O(n^2) that displays all the passes
=> Added Bubble Sort Code in C while displaying all the passes

DSA_USING_C/CircularLinkedList
Added Circular Linked List Code in C with functions like insertAtBegin, insertAtLast, display, delete
=> Added Circular Linked List Code in C

DSA_USING_C/Sorting/shell_sort.c
I have added the code C program for shell sort in the appropriate folder
=> Added shell sort code using C

DSA_USING_C/operationsonstack.c
hacktoberfest,Please merge my PR.
=> Created operationsonstack.c file in DSA_USING_C

DSA_USING_C/Subtraction_of_polynomial_using_linked_lists
I have added the code for the subtraction of two polynomials using linked lists, in C
=> Subtraction_of_polynomial_using_linked_lists

C++/Heap Sort Max Heapify.cpp
Hi! I have pulled the repo with Heap Sort Max Heapify in cpp. You can have a loop ,merge the repo and assign the hacktoberfest Labels. Thanks
=> Heap Sort with Max Heapify is added in cpp program

JAVA/mergesort.java
Hacktoberfest.Please merge my PR.
=> Created mergesort.java file.

PYTHON/N Queen Problem
Python Program for N Queen Problem
The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other
=> Create N Queen Problem

PYTHON/Naive_string_matching_Algo.py
Naive String Matching Algorithm in Python
=> Naive String Matching Algorithm

C++/BreakAPalindrome.cpp
Added C++ algorithm for Break A Palindrome.
=> Added C++ algorithm for Break A Palindrome

C++/SkylineProblem.cpp
Added code for Skyline Problem. Popular leetcode question.
=> Added code for Skyline Problem

C++/hello.cpp, C++/knapsack_problem.cpp
This is my first contribution! , please say if there are some problems.
=> Knapsack_Problem

JAVA/spiralMatrix.java
I have added the spiral matrix program of 2D Arrays in JAVA.
=> added spiral matrix program

JAVA/trappingRainwater.java
I have added a solution of the classical Trapping Rainwater problem using JAVA.
=> added trapping rainwater problem

C++/coin_change_problem.cpp
I have solved the Coin Change Problem using the Dynamic Programming approach.
=> Coin Change Problem

C++/Minimum_Square_Problem.cpp
This problem is solved by dynamic programming.
=> Minimum Square Problem

C++/DNF_sort.cpp
Also known as the sorting of 0s, 1s, and 2s.
=> DNF Sorting

C++/countGoodNodesInTree.cpp
This is a Leetcode Binary Tree Medium problem solution in C++ which uses O(n) time ans space complexity.
=> Added Code for Tree Medium problem in cpp>

JAVA/ReversalAlgorithmRotateArray.java
Here I add a program which will Rotate an Array to k Index using Reversal Algorithm.
=> ReversalAlgorithmRotateArray

C++/decimaltobinry.cpp
Added a file that converts decimal to binary in c++ language.
=> Added a file that converts decimal to binary.

C++/WaveSort.cpp
=> WaveSort.cpp added

C++/searchbst.cpp
Searches element in Binary Search Tree
@arin2002 please check it out
=> searchbst.cpp added

C++/Snake_Ladder_Problem.cpp
Hey I have added the commonly asked Snake Ladder Problem where the task is to find the least number of rolls to reach the destination
=> Added Snake Ladder Problem

C++/WordLadder1.cpp
This is a famous Word Ladder problem of graphs where we need to find the length of shortest transformation sequence from A to B, such that:
You must change exactly one character in every transformation.
Each intermediate word must exist in the dictionary.
=> Added Word Ladder 1

C++/DayToDate.cpp
This Program convert Day (1-365) to respective Date
e.g.  Day 32  will result in Feb 2
=> Day To Date

C++/NumberIntoEnglishWordClass.cpp
This program converts 0-9999 to English Words.
=> Number to English Words (0-9999)

C++/edit_distance.cpp
edit distance problem using dynamic programming
=> added edit distance problem

DSA_USING_C/Sorting/cocktail_shaker_sort.c
sorting an unsorted array of elements using cocktail shaker sort algorithm in c
=> added cocktail shaker sort

JAVA/EggDroppingPuzzle.java
Implemented Egg Dropping Puzzle
=> Create EggDroppingPuzzle .java

JAVA/Publisherbook_details.java, JAVA/matrix_codes/Multiply_matrix.java, JAVA/matrix_codes/Transpose_matrix.java, JAVA/matrix_codes/add_sub_matrix.java
Initall part i have commited few files using java codes.
=> Object oriented java programs

C++/Z Algorithm.cpp
String Linear time pattern searching Algorithm
=> Create Z Algorithm.cpp

C++/stackUsingQueue.cpp
Implementation of Stack using Queue In C++
=> Added stackUSingQueue.cpp

C++/queueUsingStack.cpp
Implementation of Queue Using Stack in C++
=> Added queueUsingStack.cpp

C++/36_Multiple_Inheritance.cpp, C++/37_Operator_Overloading.cpp, C++/anagram.cpp, DSA_USING_C/Hash_SLL.c, DSA_USING_C/Sorting/improved_bubble_sort.c
Added Multiple Inheritance, operator overloading, anagram, hash linked list & improved bubble sort.
=> Added 5 programs

PYTHON/graph1.py, PYTHON/merge_sort.py
Added 2 python programs for graph and merge sort
=> UziBytes Python

PYTHON/dictionary.py, PYTHON/list_operations.py
list operations and dictionary operations
=> <list_dictionary>

PYTHON/FibbonacciSearch.py
I have added the FibbonacciSearch algorithm in python.
=> Added fibbonacci search

PYTHON/tree_create.py, PYTHON/tree_insertion.py
root creation and inserting elements in tree
=> tree_insertion

PYTHON/inorder_traversal.py
=> inorder_traversal

PYTHON/postorder_traversal.py
Post-order traversal of a tree
=> postorder_traversal

PYTHON/preorder.py
=> preorder_traversal

Two Sum IV (Leetcode #653)
Given the root of a Binary Search Tree and a target number k, return true if there exist two elements in the BST such that their sum is equal to the given target. #653
=> Two Sum IV (Leetcode #653)

Median of Two Sorted Arrays.cpp
Find median in sorted array with time complexity O(log(m+n))
=> Median of Two Sorted Arrays Leetcode (4)

C++/shellsort.cpp
added shell sort.
please merge it
=> shellsort algorithm

C++/inorder_traversal.cpp, C++/preorder_traversal.cpp, DSA_USING_C/inorder_traversal.c, DSA_USING_C/preoder_traversal.c
=> Dsa using c

C++/Two_Sum_IV.cpp
Given the root of a Binary Search Tree and a target number k, return true if there exist two elements in the BST such that their sum is equal to the given target.
Here is its solution
=> Two_sum_IV #653 (leetcode)

Leetcode/count_and_say_daily_problem.cpp
Adding leetcode daily problem solution 38. Count and Say in C++ language.
=> Adding leetcode daily solution in cpp

C++/trie.cpp
Implemented advanced data structure Trie in cpp language. It supports insertion of string in trie, search a string in trie and can show if strings with particular prefixes present in trie or not.
=> Adding Trie Implementation in C++ Language

C++/Cocktail sort.cpp
C++ implementation of Cocktail Sort
=> Create Cocktail sort.cpp

JAVASCRIPT/Big integer sort.js
Javascript code to sort the Big integers in ascending order
=> Create Big integer sort.js

C++/Stack_using_priority_queue.cpp
Please accept my merge request
=> Create Stack Using Priority Queue

C++/Data Structures/Stack and Queue/queue.cpp
=> Added queue.cpp

DSA_USING_C/BSTFunctions.c
It has all implementations of Binary Search Tree in C
=> Added bst functions in C

C++/Object Oriented Programming/Aggregation.cpp
This program contains example of aggregation.
=> Aggregation in OOP

OOP/Object Tracker
This code tells you the Implement a class named as ObjectTracker that can track how many objects of a class are present in memory. It is increment the object counter when a new instance of the object tracker is created  and  
decrement the counter when any object is removed from the memory by using constructors and destructors
=> Create Object Tracker

Resetting Clock
This code create a Time class represent a specific time of day, storing the hours, minutes, and seconds. Include the following in the class:
 All constructors (default constructor, parametrized constructor, copy constructor) and a destructor  a function advance to advance the current time of an existing object  a function reset to reset the current time of an existing object
=> Create Resetting Clock

Leetcode/3Sum_Closest.cpp, Leetcode/4Sum.cpp, Leetcode/Group_Anagrams.cpp, Leetcode/Integer_to_Roman.cpp, Leetcode/Maximum_Subarray.cpp
I have added a few solutions of LeetCode questions.
=> LeetCode solutions

4.cpp
=> Rock Paper Scissors

C++/Extra questions/fractional_knapsack.cpp
Fractional Knapsack Problem with greedy algorithm.
=> Fractional Knapsack Problem

C++/Extra questions/window_sliding.cpp
=> Window Sliding Problem

C++/Extra questions/duplicate1.cpp
Remove_duplicates numbers in array
=> Remove_duplicates numbers in array

C++/Extra questions/Edit_distance.cpp
how many operation we have to do for making to string same
=> Edit_distance_problem

JAVASCRIPT/binary_search.js, JAVASCRIPT/linear_search.js
- Binary and Linear Search codes in JS added.
- Comments are written in every needed line of code.
- None of the rule of repo is violated.
=> Binary and Linear Search in JS added.

Calculator/README.md, Calculator/index.html, Calculator/index.js, Calculator/style.css
Hey buddy !
I added a Project "Calculator" 
if you like it please merge it into your project ...
=> Added a New project "Calculator" 

JAVA/ReverseStack.java
=> Added ReverseStack.java

JAVA/InfixToPostfix.java
=> Added InfixToPostfix.java

JAVASCRIPT/selection_sort.js
None of the repository rule is violated.
=> Added selection sort using JS

C++/Algorithms/Dynamic Programming/RodCuttingProblem.cpp
Given a rod of length n inches and an array of prices that includes prices of all pieces of size smaller than n. Determine the maximum value obtainable by cutting up the rod and selling the pieces.
=> Rod Cutting Problem

C++/Extra questions/TrappingRainWater.cpp
Given an array of N non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it is able to trap after raining.
=> Trapping Rainwater Problem

JAVASCRIPT/bubble_sort.js, JAVASCRIPT/heap_sort.js, JAVASCRIPT/insertion_sort.js, JAVASCRIPT/selection_sort.js
Code Added:
- Heap Sort
- Insertion Sort
- Bubble Sort
Note: None of the repository rule is violated.
=> added multiple sorting techniques in JS

C++/Programming basics in C++/Basic Problems in C++/AmstrongNumber.cpp
A positive integer of n digits is called an Armstrong number of order n (order is number of digits) if.  abcd… = pow(a,n) + pow(b,n) + pow(c,n) + pow(d,n) + ….
=> Amstrong Number

DSA_USING_C/kruskals.c, DSA_USING_C/prims.c
Added minimum spanning tree algorithms i.e. Prim's And Kruskal's Algorithm.
=> Added minimum spanning tree algorithms

JAVA/Mathematics/CountDigits.java, JAVA/Mathematics/divisor.java, JAVA/Mathematics/fibo.java, JAVA/Mathematics/gcd.java, JAVA/Mathematics/palindrome.java, JAVA/Mathematics/primeNo.java, JAVA/Mathematics/primefactor.java, JAVA/Mathematics/trailingZeroesFromFactorial.java
hello @arin2002  ,  I have added basic programs in JAVA/Mathematics folder
=> Basic Programs Added

C++/hashing.cpp
hii @arin2002 , I have added hashing algorithm in cpp folder and fixed #113 ,pls review my pr and do let me know if you want any changes
=> Added Hashing Algo to cpp folder

C++/Data Structures/Trees/Zig Zag Traversal Of Binary Tree.cpp
This PR is submitted under hacktoberfest.Please accept it
=> Create Zig Zag Traversal Of Binary Tree.cpp

C++/Data Structures/Trie/Power Set: Print all the possible subsequences of the String.cpp
This PR is submitted under Hacktoberfest.Please accept it.
=> Create Power Set: Print all the possible subsequences of the String.cpp

C++/Data Structures/Trees/Kth largest or smallest element in Binary Search Tree
This PR is submitted under Hacktoberfest.Please accept it
=> Create Kth largest or smallest element in Binary Search Tree

C++/Algorithms/Graph Algorithms/topoUsingIndegree.cpp
Issue #84, added graph algorithm (topo sort using Indegree)
=>  topo sort using indegree

C++/Data Structures/Linked List/reverseAlternateKnode.cpp
Issue #80, Implemented a solution for "reverse alternate k nodes problem"
=> solved a problem of alternate k nodes

C++/databaseManagement.cpp
This is a program for database management program in cpp.
=> Database Management

DSA_USING_C/Queue Operations using Linked Lists
I have added the code for enqueue and dequeue in queues using linked lists
=> Queue Operations using Linked Lists

C++/TrieDictionary.cpp
Created a Trie Dictionary in cpp.
=> TrieDictionary

DSA_USING_C/Stack Operations using Linked Lists
I have added the code for push and pop in stack using Linked Lists
=> Stack Operations using Linked Lists

C++/Algorithms/Dynamic Programming/buyAndSellStocks.cpp
=> buy and sell stocks

C++/Algorithms/Dynamic Programming/countBinaryStrings.cpp, C++/Algorithms/Dynamic Programming/countSubsequencea+b+c+.cpp, C++/Algorithms/Dynamic Programming/fibonacci.cpp, C++/Algorithms/Dynamic Programming/friendsPairing.cpp, C++/Algorithms/Dynamic Programming/frogJump.cpp
=> Dynamic Programming questions arin2002#80

C++/Algorithms/Dynamic Programming/frogJumpKdistance.cpp, C++/Algorithms/Dynamic Programming/goldmine.cpp
=> Add dynamic programming problems

C++/Algorithms/Dynamic Programming/LongestCommonSubstring.cpp, C++/Algorithms/Dynamic Programming/longestCommonSubsequence.cpp, C++/Algorithms/Dynamic Programming/longestIncreasingSubsequence.cpp
This commit includes longest common subsequence, longest common substring and longest increasing subsequence.
arin2002#80
=> Add Dp/longest common subsequence

Scala/Prime/PrimeRecursive.scala, Scala/Prime/PrimeSequence.scala
Add,
- PrimeRecursive.scala : Check a whether a given number is prime
- PrimeSequence.scala : Print Prime numbers upto given n.
=> Create recursive Prime using scala

PYTHON/python games/flames.py
=> Flames in python

Scala/CaesarCipher/CaesarCipherDencrypt.scala, Scala/CaesarCipher/CaesarCipherEncrypt.scala
Add,
**Encrypt a message by shifting its letters by some value n in the alphabet**
- CaesarCipherEncrypt: Encrypt a given phrase
- CaesarCipherDencrypt: Dencrypt a given encrypted phrase
=> Create CaesarCipher encrypt and decrypt

Scala/EvenOdd/BinaryRecursion.scala, Scala/EvenOdd/NonRecursive.scala
Add even odd using non-recusione and recusion
=> Add even odd using non-recusione and recusion

Leetcode/Reverse_Nodes_kGroup.cpp
for reversing kGroup nodes in Linked List
=> Added code

C++/longestConsecutiveSubsequence.cpp
Regarding the issue opened 
ADD DSA solutions in your language folder #404
I have added the solution to the leetcode problem find the longest consecutive susbsequence
=> Added Longest consecutive subsequence solution to C++ Folder

PYTHON/palindrome.py
Added palindrome.py file in the PYTHON language folder.
=> Added palindrome.py

JAVA/hashing/DistinctNumber.java
in this question we going  to count the distinct no in array  using  Hash Set .Time Complexity of this program is O(n);
=> COUNT DistinctNumber.java

JAVA/Anagram.java
anagram are  words which use same alphabets but have pronounced and spell differently. time complexity isO(n)
=> check if anagram

C++/Extra questions/k-th_smallest_number_in_matrix.cpp
Issue #80, added a solution for a amazon placement problem.
=>  added a solution for a problem

C++/Extra questions/kokoEatingBananas.cpp
Issue #80 , binary search problems.
=> added a problem of "binary search in ans"

Leetcode/badVersion.cpp
Issue #80, added bad version problem
=> added badVersion Problem

Leetcode/split-array-largest-sum.cpp
Issue #80, added solution for binary search problems
=> added solution for split-array-largest-sum

C++/Extra questions/minimum-round-to-complete-all-task.cpp
Issue #80 , solution with greedy approach
=> added solution of greedy problem

Leetcode/genrateParentheses.cpp
issue #404,  solved genrate parentheses problem
=> genrate parentheses

Kotlin/check-value-in-range.kt
=> check-value-in-range.kt

Kotlin/arithmetic-operations.kt
Add, Subtract, Multiply and Divide operations performed in this code
=> arithmetic-operations.kt

Kotlin/while-loop.kt
++i statement inside the while loop. After 5 iterations, variable i will be incremented to 6. Then, the test expression i <= 5 is evaluated to false and the loop terminates.
=> while-loop.kt

C++/Extra questions/Calculating_Exponential.cpp
In this program, we calculate a^b efficiently using recursion.
=> Calculating Factorials

C++/Extra questions/Sum_n_numbers.cpp
In this question, we will calculate the sum to N numbers.
=> Sum of N Numbers

leftmost.java
anagram are  words which use same alphabets but have pronounced and spell differently. time complexity isO(n)
=> find the leftmost repeating character in a  string

JAVASCRIPT/reduce.js
#404  can you merge my example
=> reduce.js examples

C++/Extra questions/Reversing_String.cpp
Reversing a given string using recursion.
=> Reverse String

C++/Data Structures/Linked List/Merge_sort_LL.cpp
Merge Sort using Linked List data structure.
=> Merge Sort

C++/Data Structures/Linked List/Midldle_element_of_Linked_List.cpp
Finding the middle element of the linked list.
=> Middle Element Of Linked List

C++/Data Structures/Linked List/Binary_search.cpp
Binary Search using Linked List data structure.
=> Binary Search

insertionSort.c
Sorts a doubly linked list of integers in ascending order using the Insertion sort algorithm
=> Added Insertion Sort Algorithm

C++/Extra questions/Kth_smallest.cpp
Kth Smallest element using heap data structure.
=> Kth Smallest Element

C++/Extra questions/Heapify.cpp
=> Heapify Function

JAVASCRIPT/fibonacci.js
#404 i added fibonacci finder with 3 solution
=> find fibonacci number

C++/allPermutationOfString.cpp, C++/towerOfHanoi.cpp
added solutions for tower of hanoi and all permutation of string in cpp
=> added solution to c++ folder

C++/Extra questions/Tries.cpp
Added Tries code in c++ folder.
Issue : #401
=> Added Tries

JAVA/StepsToReturn0.java
@arin2002 I have added a program to calculate the number of steps required to reduce a number to 0.
=>  added program to calculate the number of steps required to reduce a number to 0

C++/Basic Problems in C++/Program To Rotate An Array in Anticlockwise direction.txt
Hello.
myself kratik.
I want to add a C++ program to rotate an array in anticlockwise direction. I am new to open source and looking forward to complete hacktoberfest by making this contribution.
Thank You,
#hactoberfest2022
=> Program To Rotate An Array in Anticlockwise direction

C++/Object Oriented Programming/Maximum_Sum_Subarray_Problem.cpp
The problem differs from the problem of finding the maximum sum subsequence. Unlike subsequences, subarrays are required to occupy consecutive positions within the original array.We can easily solve this problem in linear time using Kadane’s algorithm. The idea is to maintain a maximum (positive-sum) subarray “ending” at each index of the given array. This subarray is either empty (in which case its sum is zero) or consists of one more element than the maximum subarray ending at the previous index.
=> added Maximum Sum Subarray Problem

PYTHON/iron_man.py
Hey! I have created iron man jarvis AI assistant..Please merge it into your repo.
=> iron_man_jarvis.py

C++/Data Structures/Trees/postorder_traversal.cpp
Please merge my pull request and add "hacktoberfest-accepted" tag to it.
=> Added postorder traversal code in trees in data structures cpp

C++/Extra questions/fascinating_number.cpp
please merge my request and add "hacktoberfest-accepted" tag to it.
=> Added Fascinating Number code to extra questions in CPP folder

Leetcode/FindTheDifference.cpp
I have added a new code file #4
=> added Find the difference file

Leetcode/Subsets.cpp
I have added a new file for Subsets problem #4
=> Add new file for Subsets

Leetcode/Remove_Duplicates_from_sorted_array.cpp
simple cpp code for removing the duplicates in the array
=> Code for Hacktoberfest leetcode

C++/MinMaxHeap.cpp
Implemented Min-Max Heaps in C++.
These data structures support Insertion, deleting-minima, and deleting maxima in O(log n) time. It also supports Finding Minima and Finding Maxima in O(1) time.
=> Create Min-Max Heaps

JAVA/NumberOfSteps.java
Here I've solved one problem statement from Leetcode. The code comprises an error-free solution annotated with relevant comments.
Problem Statement and Solution are well explained. Looking forward to your response.
=> created NumberOfSteps.java (Leetcode PS)

C++/PlaceNQueen.cpp
Added code to problem number of ways to place n queen on nxn board.
=> Create placenqueen file

C++/longest_common_subsequence.cpp
@galmeida125 please merge my pull request
=> added code for longest common subsequence

Leetcode/7_ReverseInteger.cpp
=> Added code for Q7. Reverse Integer of Leetcode

Leetcode/46_Permutations.cpp
Solved Q46. Permutations of Leetcode
=> Added solution for Q46. Permutations of Leetcode

Unique Paths with Obstacles.cpp
@galmeida125 please merge my pull request.
=> added code for Unique Paths with Obstacles for cpp

Leetcode/74_Searcha2DMatrix.cpp
Created solution for 74. Search a 2D Matrix
=> Solution of Q74. Search a 2D Matrix

Leetcode/198_House Robber.cpp
Added Solution of Q198. House Robber of Leetcode
=> Leetcode 198. House Robber

Leetcode/240_Searcha2DMatrix_II.cpp
Created Solution for Leetcode Q240. Search a 2D Matrix II
=> Leetcode Q240. Search a 2D Matrix II

C++/leftviewofabinarytree.cpp
@arin2002 Sir please merge the PR under Hacktoberfest tag
=> added code for left view of binary tree

c/Tries.c
=> Added Tries.c

C++/Magic_square_generator.cpp
@arin2002 Sir please merge the PR under Hacktoberfest tag
=> added magic square generator code

JAVA/two_sum.java
Here we are Using Brute-Force ,A naive solution is to consider every pair in the given array and return if the desired sum is found. This approach is demonstrated below in C, Java, and Python:
=> added Two Sum Probelm

Leetcode/lowestCommonAncestor.java
Added a leetcode qn to find the lowest common ancestor (LCA) node of two given nodes in the Binary Search Tree.
=> Java code to find Lowest Common Ancestor of a Binary Search Tree

Leetcode/deleteMiddle.java
Added leetcode qn to delete the middle node, and return the head of the modified linked list, given the head of a linked list.
=> Code to Delete the Middle Node of a Linked List

PYTHON/Line drawing algorithm/bla.py, PYTHON/Line drawing algorithm/dda.py
Bresenham's Algorithm and Digital Differential Line Drawing Algorithm
=> Created two line drawing algorithm called BLA and DDA for computer graphics

C++/Data Structures/Trees/Valid BST or not
Cheaking that a random tree is binary search tree  or not.
=> valid BST or not

Leetcode/valid_sudoku.cpp
Adding solution of problem number 36 in leetcode Valid Sudoku
=> Adding solution of Valid Sudoku problem in cpp

Leetcode/pacific-atlantic-waterflow.cpp
Adding solution if leetcode problem number 417 Pacific Atlantic Water flow. Solved using the concept of breadth first search.
=> Adding CPP solution of Pacific Atlantic Water Flow problem of leetcode

JAVA/CountZeroes.java
Here, I have added a java program to count the number of zeroes in a number using recursion.
=> added java program to count the number of zeroes in a number

Leetcode/valid_sudoku.cpp
Added Question of the leetcode problem Valid Sudoko and giving the main function to run the the solution function and also added appropriate test cases of the problems
=> Modifying valid sudoku problem solution

C++/Data Structures/Trees/largest BST
to find largest Binary Search Tree in a given binary tree
=> finding largest bst

C++/Continuous_Subarray_Sum.cpp
Created the PR for this open issue #4 
Kindly review and let me know if any changes are required.
Thanks!!
=> Added Todays Leetcode solution in CPP (https://leetcode.com/problems/continuous-subarray-sum/)

C++/Algorithms/Dynamic Programming/wildcard_matching.cpp
Created the PR for this open issue #404 
Kindly review and let me know if any changes are required.
Thanks!!
=> Added DP problem Wildcard matching in the folder(https://leetcode.com/problems/wildcard-matching/)

JAVA/BruteForceDivideConquer/Faktorial.java, JAVA/BruteForceDivideConquer/MainPangkat.java, JAVA/BruteForceDivideConquer/Pangkat.java
=> i added a program about BruteforceDivideconquer

Leetcode/Break the palindrome .cpp, Leetcode/Contains Duplicates II.cpp, Leetcode/Find the index of first OCcurance in a string.py
adding tomorrow problem as well...
=> added some leetcode problems

C++/Combination_Sum.cpp
Added Combination Sum problem in C++ folder
=> CombinationSum

C++/Image_Overlap.cpp
Created the PR for this open issue #4 
Kindly review and let me know if any changes are required.
Thanks!!
=> Added Leetcode daily question Image Overlap(https://leetcode.com/problems/image-overlap/)

C++/Data Structures/Linked List/reverse_in_groups_k
Reverse linked list in groups of size k in linked list folder for this open issue #404 
This is done as a part of Hacktoberfest 2022
Kindly review the same and let me know if any changes are required
Thanks!
=> Added code for Reverse linked list in groups of size k 

PYTHON/python games/hangman.py
Adding Hangman game developed using Python to the "Coding-questions/PYTHON/python games" directory.
=> Adding Hangman game developed in Python

C++/DP/form a palindrome.cpp
Added a code to form a palindrome of dp,kindly merge.
=> Create form a palindrome.cpp

Linked List/clone a linkedlist.c
Added a code for clone a linked list , kindly merge.
=> Create clone a linkedlist.c

C++/Data Structures/Linked List/Clone_Linked_list_random_pointers.cpp
Created PR for the issue #404  added CPP code for clone linked list with random pointers in Linked list folder
Link : https://leetcode.com/problems/copy-list-with-random-pointer/
Kindly review and let me know if any changes are required 
Thanks
=> Added code for clone linked list with random pointers

C++/QuickSort.cpp
QuickSort file in C++ file added
=> quick sort

Leetcode/Car pooling.cpp, Leetcode/Flower Planting With No Adjacent.cpp, Leetcode/Remove All Adjacent Duplicates In String.cpp, Leetcode/day of the year.cpp
=> Leetcode Cpp questions

Leetcode/1985. Find the Kth Largest Integer in the Array.cpp
Implemented an optimised approach to the given problem, using sort fuction of the STL in C++.
=> 1985. Find the Kth Largest Integer in the Array

C++/Data Structures/Linked List/find_node_in_LL
=> Find a node in linked list

C++/Binary search tree/Find-Path-in-BST
=> Find Path in BST

C++/BinaryTreeMaxPathSum.cpp
=> Tree Medium Problem 

C++/serialiseDeserialiseBinaryTree.cpp
=> Tree Problem

C++/Graph/prims_algo
=> Prims algorithm

C++/Graph/Kruskals_algo
=> Kruskals Algorithm

C++/Tree/Count_leaf_nodes
=> Count Leaf Nodes

C++/Tree/Postorder_Traversal
=> Postorder Traversal

C++/Tree/Node_with_max_child_sum
=> Node with max child sum

C++/Tree/Structurally_identical
=> Structurally Identical

C++/graphs/Get_connected_components
=> Get Connected Components

C++/graphs/BFS_Traversal
=> BFS Traversal

C++/Tree/Print_zigzag
=> Print ZigZag

C++/Tree/Tree_from_postorder_and_inorder
=> Create Tree from Postorder and Inorder

Leetcode/115_DistinctSubsequences.cpp
Added the problem solution for Leetcode problem 115. Distinct Subsequences in C++.
=> Distinct Subsequences

breadth_first_search.cpp
Added Breadth First Search Code which is Graph traversal method (or Algorithm)
=> Added Breadth First Search Code

C++/Tree/Height_of_Tree
=> Height of Tree

C++/Tree/Mirror_Tree
=> Mirror Tree

C++/Merge_2_LLs
=> Merge 2 Linked Lists

C++/Reverse_LL
=> Reverse a Linked List

C++/Binary search tree/BST_from_sorted_LL
=> BST from sorted Linked List

C++/Extra questions/Prime_Factorization_Number_and_Sum_of_divisors.cpp
Added Prime Factorization of Number and Sum of its divisors in most time efficient, and user interactive way in C++.
=> Added Prime Factorization of Number and Sum of its divisors

C++/DP/Staircase_problem
=> Staircase Problem

C++/DP/Min_steps_to_1
=> Min steps to 1

C++/DP/Edit_Distance
=> Edit Distance

C++/DP/LIS
=> Longest Increasing Subsequence

C++/Algorithms/binary Search/lower_bound.cpp, C++/Algorithms/binary Search/upper_bound.cpp
Added lower bound  and Upper bound of a target number in the Given array in C++ without using builtin upper_bound and lower_bound
=> Added lower bound and Upper bound Code

C++/Data Structures/Linked List/Flattening_LL.cpp, C++/Group_Anagrams.cpp
Created PR for the issue #4 
Link : https://leetcode.com/problems/group-anagrams/
Kindly review and let me know if any changes are required
Thanks
=> Added todays Leetcode Group Anagrams

JAVA/recursion/OptimisedFibonacciSeries.java
This code of fibonacci series works in linear time complexity O(1)
=> Added Optimised Fibonacci Series Formula

C++/dec_to_binary.cpp
Hii @arin2002 ,I have added decimal to binary file in c++ folder ,pls review my pr and do let me know if any changes you want
=> Added dec to bin file

c/co_prime.c
hii @arin2002 ,I have added co-prime in c folder ,pls review my pr and do let me know if any changes you want
=> Added co_prime in c

C++/Dynamic Programming/cherryPickup.cpp
=> cherry pickup problem

C++/Graph/distinctIslands.cpp
=> distinct islands

C++/array/FindLargestElementofArray.cpp
Hi,
I have been assigned https://github.com/arin2002/Coding-questions/issues/401 and have written a basic C++ program to find the largest number in an array.. Kindly review it..
Issue: ADD C++ program to c++ folder #401(https://github.com/arin2002/Coding-questions/issues/401)
=> C++ program to find largest element in an array

C++/BST/insertInBst.cpp
=> inserting elements in bst

CSharp/dayGuess.cs
algorithm to guess day of birthday from question
=> Hacktoberfest !! guess day of birthday from question

Leetcode/distinctIntegerafterReverse.cpp
Hii @arin2002 ,I haved added solution for this question in Leetcode  
https://leetcode.com/contest/weekly-contest-315/problems/count-number-of-distinct-integers-after-reverse-operations/
Pls review my pr and do let me know if any changes you want.
=> Added leetcode file

JAVA/Area And Perimeter/diamond_pattern.java
Hii @arin2002 , I have added  diamond pattern file in java ,pls review my pr and do let me know if any changes you want.
=> Added pattern file

C++/Earliest_possible_day_bloom.cpp
Created PR for the issue #4 
Link : https://leetcode.com/problems/earliest-possible-day-of-full-bloom/
Kindly review and let me know if any changes are required
Thanks
=> Added code for todays Leetcode Earliest possible full bloom day

Data Structures using C++/priorityQueue.cpp
Priority Queue is an abstract data type which is a collection of elements where the elements have different priority levels. The elements with higher priority is processed before any element of lower priority. If there are elements with the same priority then the element added first in the queue would get processed first. Here this implementation has operations of addition,  deletion,  display, and sorting according to priority .
=> Priority Queue implementation | C++

Data Structures using C++/huffmanCode.cpp
Greedy is an algorithmic paradigm that builds up a solution piece by piece, always choosing the next piece that offers the most obvious and immediate benefit. So the problems where choosing locally optimal also leads to global solution are the best fit for Greedy. For example consider the Fractional Knapsack Problem. The local optimal strategy is to choose the item that has maximum value vs weight ratio. This strategy also leads to a globally optimal solution because we are allowed to take fractions of an item. One of the Standard Greedy Algorithms is the Huffman Coding Algorithm. The Huffman Coding Algorithm is a lossless data compression mechanism. It is also known as data compression encoding. It is widely used in image (JPEG or JPG) compression. We know that each character is a …
=> Greedy Algorithm | Huffman Coding | C++

PYTHON/shannon_fano.py
Added the shannon fano algorithm for data compression
=> Added shannon fano algorithm

Data Structures using C++/Answer68.cpp
Given a snake and ladder board, find the minimum number of dice throws required to reach the destination or last cell from the source or 1st cell. Basically, the player has total control over the outcome of the dice throw and wants to find out the minimum number of throws required to reach the last cell. If the player reaches a cell which is the base of a ladder, the player has to climb up that ladder and if reaches a cell is the mouth of the snake, and has to go down to the tail of the snake without a dice throw. It will take input from user about no of ladders and no of snakes and their position from one point to another and then gives the minimum moves required to reach 100 in snake and ladder game.
=> Snake & Ladder problem | Graph Data Structure

c/Shell_sort.c
Added code for shell sort using C
=> Added shell sort

c/Polynomial_Subtraction.c
Added code of polynomial subtraction using linked list in C
=> Polynomial Subtraction.c

c/Stack_Implementation_using_LinkedLists
Added code of push and pop using linked lists in C
=> Stack_Implementation_using_LinkedLists

C++/LeetCode/523. Continuous Subarray Sum.cpp
-> LeetCode Medium 
-> O(n) Optimized approach 
-> faster than 99.90% of C++ online submissions
=> 523. Continuous Subarray Sum

C++/LeetCode/33. Search in Rotated Sorted Array.cpp
-> LeetCode Medium
-> O(log n) optimized approach
-> Using Binary Search Algorithm
=> 33. Search in Rotated Sorted Array

Leetcode/100. Same Tree.cpp
-> Function to check if two Trees are the same or not.
-> Optimized Approach
-> Using Recursion
=> 100. Same Tree LeetCode

Leetcode/19. Remove Nth Node From End of List.cpp
-> LeetCode Medium
-> Given the head, remove the nth node from the end 
-> Optimized Approach
=> 19. Remove Nth Node From End of List

JAVA/Dynamic Programming/Longest-Common-Subsequence-Iterative.java, JAVA/Dynamic Programming/Longest-Common-Subsequence-Recursive.java
Added recursive and iterative longest common subsequence solution in java dynamic programming
=> Added longest common subsequence solution in java dynamic programming

C++/Data Structures/Trees/CS21B1008_threaded_binary_tree.cpp
Implemented In-order Traversal in Threaded Binary Trees
=> Added Threaded Binary Tree

C++/Data Structures/Heap_sort.cpp
Heap Sort an array of integers
=> Added Heap_Sort.cpp

C++/Heap/Heap.cpp
Implementation of Heap Data Structure
=> Added Haep.cpp

pseudosort.py
=> Hacktoberfest

C++/Basic Problems in C++/HelloWorld.c++
Hello Hacktoberfest World. My new beginning into c++.
=> Hello Hacktoberfest World

c/mergesort.c
added code of merge sort using c
=> mergesort.c

c/countsort.c
added the code for count sort in c
=> countsort.c

c/fibonacci.c
added the code for fibonacci series in c
=> fibonacci.c

c/binarysearch.c
added the code for binary search in c
=> binarysearch.c

PYTHON/Automate-Google-Form-Filling/fill_google_form.py
Added a Script that automate google form filling using selenium script
=> added automate google form filling

C++/AlgoExpertQuestion/ThreeNumberSum.cpp, C++/AlgoExpertQuestion/TwoNumberSum.cpp
I have added two problem:
1. TwoSum problem in C++ with Solution
2. ThreeSum problem in C++ with Solution
=> twoSum and threeSum in C++

PYTHON/HACKERCUP2022_1_A_1_Consecutive_Cuts_-_Chapter_1.py, PYTHON/Meta_Hackercup_A_Second12.py
Meta Hackercup2022 python solution
=> Meta Hackercup2022 python solution

C_1_Second_Meaning.cpp, PYTHON/hackercup2022_B_1_Second_Friend.py
Meta Hackercup2022 CPP solution
=> Meta Hackercup2022 cpp solution

PYTHON/blinkeye.py
Computer vision Eye blink program, that ring a voice alert! for patients.
=> Computer vision Eye blink program

C++/LeetCode/2.swappingNodesInLinkedList.cpp
Issue #404 , added swapping node problem and solution
=> swapping nodes problem

C++/LeetCode/6.rotateList.cpp
Issue #404 , added rotate list problem
=> rotateList problem

C++/LeetCode/8.maximum69Number.cpp
Issue #404 added maximum 69 number problem
=> added maximum 69 number problem

C++/LeetCode/Pascal's Triangle - 118/9.findTargetAfterSorting.cpp
Issue #404 , added find target indices after sorting
=> added find target indices after sorting

C++/LeetCode/10.numberOfArithmeticTriplet.cpp
Issue #404 added number of arithmetic triplet problem
=>  added number of arithmetic triplet problem

C++/Toeplitz_Matrix.cpp
I have added the code as a part of hacktoberfest 2022 in C++ for this issue #4 
Kindly review and let me know if any changes are required
Thanks!
=> Added todays leetcode question

hacktoberfest/Circular_Doubly_Linked_List.cpp, hacktoberfest/Circular_Doubly_Linked_List.py, hacktoberfest/Decision_Tree.py, hacktoberfest/Dynamic_Queue.java, hacktoberfest/Floyd_Warshall_Algorithm.cpp, hacktoberfest/Floyd_Warshall_Algorithm.go, hacktoberfest/Floyd_Warshall_Algorithm.java, hacktoberfest/Floyd_Warshall_Algorithm.py, hacktoberfest/Hashing.c
=> Hacktoberfest 2023-aditya

Leetcode/785._Is_Graph_Bipartite.cpp
Added accepted solution to 785. Is Graph Bipartite? problem on LeetCode
=> Created 785._Is_Graph_Bipartite.cpp

Leetcode/403_Frog_Jump.cpp
Added accepted solution to LeetCode Hard problem 403. Frog Jump
=> Created 403_Frog_Jump.cpp

Data Structures using C++/Binary Trees/CheckIdentical.cpp
Program to check if two given binary tree are identical or not
=> added a C++ program: CheckIdentical

PYTHON/heaps_algorithm.py
=> heaps algo added

PYTHON/heaps_algorithm_iterative.py
=> heap algorithm iterative added

PYTHON/dynamic_programming/matrix_chain_multiplication.py, PYTHON/longest_palindromic_subsequence.py
=> new programs added 

PYTHON/strassen_matrix_multiplication.py
=> stassen multiplication added.py

PYTHON/bitmask.py
=> bitmask.py added

C++/LeetCode/475_heaters.cpp
I added excepted solution to problem 475_Heaters on Leetcode
=> Created 475_heaters.cpp

C++/2750. Ways to Split Array Into Good Subarrays.cpp
Added accepted solution to leetcode problem 2750. Ways to Split Array Into Good Subarrays
=> Created 2750. Ways to Split Array Into Good Subarrays.cpp

Leetcode/30_Substring_with_Concatenation_of_All_Words.cpp
Added Accepted  Solution to LeetCode problem 30
=> Created 30_Substring_with_Concatenation_of_All_Words.cpp

Leetcode/891_Sum_of_Subsequence_Widths.cpp
Added accepted solution to problem 891 on LeetCode
=> Created 891_Sum_of_Subsequence_Widths.cpp

JAVA/towerOfHanoi.java, c/Stack/SXstack.c
Given a string containing n S’s and n X’s where S indicates a PUSH operation 
and X indicates a POP operation, and with the STACK initially empty, formulate 
a rule to check whether a given string S of operations is admissible or not.
=> Implemented a DSA problem of stack using array
